"""add_voice_timbres_table

Revision ID: 3d7944bf1dae
Revises: 9c4b1a2d3e5f
Create Date: 2026-02-11 15:18:07.060356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import UTCDateTime


# revision identifiers, used by Alembic.
revision: str = '3d7944bf1dae'
down_revision: Union[str, Sequence[str], None] = '9c4b1a2d3e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_timbres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('preview_url', sa.String(length=512), nullable=True),
    sa.Column('supported_models', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('create_time', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_timbres'))
    )
    with op.batch_alter_table('voice_timbres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_timbres_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_timbres_voice_id'), ['voice_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_timbres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_timbres_voice_id'))
        batch_op.drop_index(batch_op.f('ix_voice_timbres_id'))

    op.drop_table('voice_timbres')
    # ### end Alembic commands ###
