openapi: 3.1.0
info:
  title: DouDouChat - Friend API
  description: OpenAPI specification for the friend module
  version: 1.0.0
paths:
  /friends/:
    get:
      summary: Read Friends
      description: Retrieve friends.
      operationId: read_friends_friends__get
      parameters:
      - name: skip
        in: query
        required: false
        schema:
          type: integer
          default: 0
          title: Skip
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          default: 100
          title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Friend'
                title: Response Read Friends Friends  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      summary: Create Friend
      description: Create new friend.
      operationId: create_friend_friends__post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FriendCreate'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Friend'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /friends/{friend_id}:
    get:
      summary: Read Friend
      description: Get friend by ID.
      operationId: read_friend_friends__friend_id__get
      parameters:
      - name: friend_id
        in: path
        required: true
        schema:
          type: integer
          title: Friend Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Friend'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    put:
      summary: Update Friend
      description: Update a friend.
      operationId: update_friend_friends__friend_id__put
      parameters:
      - name: friend_id
        in: path
        required: true
        schema:
          type: integer
          title: Friend Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FriendUpdate'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Friend'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      summary: Delete Friend
      description: Delete a friend.
      operationId: delete_friend_friends__friend_id__delete
      parameters:
      - name: friend_id
        in: path
        required: true
        schema:
          type: integer
          title: Friend Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Friend'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Friend:
      properties:
        name:
          type: string
          maxLength: 64
          title: Name
          description: 好友名称
        description:
          anyOf:
          - type: string
            maxLength: 255
          - type: 'null'
          title: Description
          description: 好友描述
        system_prompt:
          anyOf:
          - type: string
          - type: 'null'
          title: System Prompt
          description: 系统提示词
        is_preset:
          type: boolean
          title: Is Preset
          description: 是否为系统预设
          default: false
        id:
          type: integer
          title: Id
        create_time:
          type: string
          format: date-time
          title: Create Time
        update_time:
          type: string
          format: date-time
          title: Update Time
        deleted:
          type: boolean
          title: Deleted
      type: object
      required:
      - name
      - id
      - create_time
      - update_time
      - deleted
      title: Friend
    FriendCreate:
      properties:
        name:
          type: string
          maxLength: 64
          title: Name
          description: 好友名称
        description:
          anyOf:
          - type: string
            maxLength: 255
          - type: 'null'
          title: Description
          description: 好友描述
        system_prompt:
          anyOf:
          - type: string
          - type: 'null'
          title: System Prompt
          description: 系统提示词
        is_preset:
          type: boolean
          title: Is Preset
          description: 是否为系统预设
          default: false
      type: object
      required:
      - name
      title: FriendCreate
    FriendUpdate:
      properties:
        name:
          anyOf:
          - type: string
            maxLength: 64
          - type: 'null'
          title: Name
        description:
          anyOf:
          - type: string
            maxLength: 255
          - type: 'null'
          title: Description
        system_prompt:
          anyOf:
          - type: string
          - type: 'null'
          title: System Prompt
        is_preset:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Is Preset
      type: object
      title: FriendUpdate
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
